# Generated by Django 3.2 on 2021-04-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcotest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['question_id', 'weight_answer'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['num_question'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='answer',
            new_name='answer_0',
        ),
        migrations.AddField(
            model_name='answers',
            name='answer_1',
            field=models.CharField(default=1, max_length=300, verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='answer_2',
            field=models.CharField(default=1, max_length=300, verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='answer_3',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='questions',
            name='var_answer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='alcotest.answers'),
        ),
    ]
