# Generated by Django 3.2 on 2021-04-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcotest', '0002_auto_20210416_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_4',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ответ'),
        ),
    ]
