# Generated by Django 3.2 on 2021-04-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcotest', '0003_answers_answer_4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['weight_answer'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alcotest.questions'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='var_answer',
        ),
        migrations.AddField(
            model_name='questions',
            name='var_answer',
            field=models.ManyToManyField(to='alcotest.Answers'),
        ),
    ]
