# Generated by Django 3.2 on 2021-04-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcotest', '0004_auto_20210416_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_1',
            field=models.CharField(max_length=300, verbose_name='Ответ  '),
        ),
        migrations.RemoveField(
            model_name='answers',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.ManyToManyField(to='alcotest.Questions'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='var_answer',
        ),
        migrations.AddField(
            model_name='questions',
            name='var_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='alcotest.answers'),
            preserve_default=False,
        ),
    ]
