# Generated by Django 3.2 on 2021-04-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcotest', '0005_auto_20210416_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='var_answer',
        ),
    ]
