# Generated by Django 3.2 on 2021-04-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcotest', '0006_remove_questions_var_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer_0',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_4',
        ),
        migrations.AddField(
            model_name='questions',
            name='var_answers',
            field=models.ManyToManyField(to='alcotest.Answers'),
        ),
        migrations.RemoveField(
            model_name='answers',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='alcotest.questions'),
            preserve_default=False,
        ),
    ]
