# Generated by Django 3.2 on 2021-04-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcotest', '0008_remove_answers_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='alco_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип алкоголя'),
        ),
    ]
