# Generated by Django 3.2.7 on 2021-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(default='no author', to='books.Author', verbose_name='Автор'),
        ),
    ]
